.TH lsi-getconf 1 "Feb 8, 2024" "Send files to slack"

.SH NAME
lsi-getconf
\- Read the browser database to try to find the cookie and token that are necessary to set up localslackirc.

.SH SYNOPSIS
lsi-getconf [OPTIONS]

.SH DESCRIPTION
This command reads the browser database to try to find token and cookie that are necessary to localslackirc.
.br
For now it only supports Firefox.
.br
This is experimental. It might not work on your machine. In which case you should fall back to extracting the data directly from the browser.
.SS Options:
.TP
.B -h, --help
Show the help message and exit.

.TP
.B --mozilla-dir DIRECTORY
Alternative search path for the mozilla directory. It defaults to ~/.mozilla.

.SH "Known errors"
.TP
.B database is locked
Close the browser to solve this issue.

.SH "SEE ALSO"
.BR localslackirc (1)


.SH WEB
.BR https://github.com/ltworf/localslackirc

.SH AUTHOR
.nf
Salvo "LtWorf" Tomaselli <tiposchi@tiscali.it>
